### ISSUE TITLE
Css declarations end in a colon versus a semicolon.

### ISSUE THREAD

**Issue by bcharan** [P233/Emmet-Css-Snippets-for-Sublime-Text-2#1]
Not sure why, but for some reason emmett css is adding a colon after my css declarations.

It could be because I'm using code intel as well, not sure.

But if I type:  

float: left;

It will autocomplete and end with a : instead of ;

**Comment by P233** [comment]
I have checked the files and it is ok.

Please Open the Sublime Text 2 Packages folder and find the fll.sublime-snippet file in `Emmet Css Snippets/Css/Visual Formatting/`.

Check the content tag. If it is displaying `float: left:`, the file must be changed by some reason, please re-install this plugin.

If the file is ok. It's probably because not compatible with other plugins. Please disable the  code intel plugin and try again.

Tell me which plugins you are using. I'd like to see the problem :)
