### ISSUE TITLE
CSS and SASS

### ISSUE THREAD

**Issue by alimd** [P233/Emmet-Css-Snippets-for-Sublime-Text-2#2]
Why you have separate folder for css and sass ?
for example in font > fef.sublime-snippet
you can combine it

```
<snippet>
    <content><![CDATA[
font-effect: 
]]></content>
    <tabTrigger>fef</tabTrigger>
    <scope>source.css, source.scss, source.sass</scope>
    <description>font-effect</description>
</snippet>
```

i want to add stylus support and pull request
if you want i can migrate this 2 folder

**Comment by P233** [comment]
Hi AliMD

Thank you very much for your intention to add stylus support! That will be great!

The CSS folder contains snippets for CSS, LESS, and SCSS. I sorted this folder first, then use find and replace feature to remove all brackets and semicolons，and replace the scope selector for Sass indented syntax. So there are two folders. Most of the snippets are different, only a few snippets which don't contain property value can be merged. … I just checked, there are 124 repeat snippets, that isn't a small amount. I'd like to merge them tonight, and I think it is necessary to leave the Sass folder for indented syntax.

I haven't used stylus before, as I know stylus can accept both regular CSS syntax and indented syntax. So, I am wondering if is it possible to support two different syntax, because both of them will use same scope selector.

Kind regards,
