### ISSUE TITLE
CSS color definitions

### ISSUE THREAD

**Issue by thamas** [P233/Emmet-Css-Snippets-for-Sublime-Text-2#9]
In pure emmet you can use `c#ef` `[tab]` to define `color: #efefef`. In this plugin you changed the shortcut to `col`. However `col#ef` `[tab]` does not works.

**Comment by P233** [comment]
Sorry @thamas, This package is only a [snippets](http://docs.sublimetext.info/en/latest/extensibility/snippets.html) collection for Emmet CSS, it doesn't support any functions. Actually it was originally created for Zen Coding in order to have the completions popup hits. Then the Emmet was released and I made a few changes to keep updated. Now I am using both the functionalities of Emmet and the snippets of this package for better efficiency :)

**Comment by thamas** [comment]
I use https://github.com/sergeche/emmet-sublime plus this package and [your sass syntax highlighting package](https://github.com/P233/Syntax-highlighting-for-Sass). So can I config these some way to make emmet css color functions work?

**Comment by P233** [comment]
I think you don't need to do anything to make them work together. I've only done two changes in the Emmet settings.

```
{
  "show_css_completions": false,
  "disabled_keymap_actions": "reflect_css_value"
}
```

I prefer my CSS snippets so I turned off the Emmet completions hits. If I need the Emmet function such as `w100p` or `c@ef` just type them and then press <kbd>Tab</kbd>, that works fine. For the second changes, please see [https://github.com/sergeche/emmet-sublime/issues/266](https://github.com/sergeche/emmet-sublime/issues/266)

If you got any problem just let me know :)
